import type { RecommendationSource } from '../types';

interface Props {
  readonly source: RecommendationSource;
}

// Exhaustiveness sentinel — if source grows beyond 'rule' | 'ai', TS errors here.
function assertNever(_x: never): null {
  return null;
}

export function RecommendationSourceBadge({ source }: Props): React.ReactElement | null {
  if (source === 'rule') return null;
  if (source === 'ai') {
    return (
      <span
        title="This insight was generated by AI, based on your logged habit data. No external data is shared."
        className="inline-flex items-center rounded-full border border-purple-500/40 bg-purple-900/20 px-2 py-0.5 text-[10px] font-medium text-purple-400 cursor-help"
      >
        AI insight
      </span>
    );
  }
  return assertNever(source);
}
